"""Textos e escolhas visuais dos carrosséis editoriais v5 (09/10/2026).

Mesmos fatos conferidos de `conteudo.py`; títulos dos itens reescritos como frases que
se sustentam sozinhas (o slide 2 é a "segunda capa" que o Instagram reexibe).
Cada item: (título com <em>, texto com <span class="mt">, selo da base legal).
"""

CARROSSEIS = {
    "outubro-rosa-trabalho": {
        "tag": "Outubro Rosa", "area": "Trabalhista",
        "capa": ("Os direitos da trabalhadora", "5 direitos", "que quase ninguém usa",
                 'Exames, FGTS e proteção contra demissão: o que a lei garante <span class="mt">neste Outubro Rosa</span>.', "Lei 15.377/2026"),
        "itens": [
            ("Mamografia não pode virar<br><em>desconto</em> no salário", 'Até 3 dias por ano para exames preventivos de câncer, <span class="mt">sem desconto</span>. Leve o comprovante da clínica.', "CLT, art. 473, XII"),
            ("A empresa tem que<br>falar de <em>prevenção</em>", 'A lei obriga as empresas a divulgar <span class="mt">campanhas de prevenção ao câncer</span> e de vacinação contra o HPV.', "Lei 15.377/2026"),
            ("O diagnóstico<br>libera o <em>FGTS</em>", 'Câncer da trabalhadora ou de um dependente permite <span class="mt">sacar o saldo do FGTS</span>.', "Lei 8.036/1990, art. 20, XI"),
            ("Demissão por causa<br>da <em>doença</em>", 'A Justiça presume discriminatória a dispensa de quem tem doença grave. <span class="mt">Pode gerar reintegração.</span>', "Súmula 443 do TST"),
            ("Confira a <em>convenção</em><br>da sua categoria", "Muitos acordos coletivos garantem mais. Confira na sua:", ""),
        ],
        "checklist": ["Estabilidade após o afastamento", "Dias para acompanhar exames", "Complemento do auxílio-doença"],
        "fecho": ("Cuidar da saúde<br>é <em>direito</em>.", "Não é favor da empresa.", "mande para uma colega de trabalho."),
        "objetos": ["corte-estetoscopio.png", "corte-laco2.png", "corte-reais.png"],
        "foto5": ("outubro-rosa-trabalho", 17), "leticia": ("leticia-real-sentada.png", "leticia-real-sorrindo.png"),
    },
    "cancer-inss": {
        "tag": "Outubro Rosa", "area": "Previdenciário",
        "capa": ("Câncer de mama e INSS", "5 direitos", "que você pode pedir hoje",
                 'Benefício sem carência, isenção de IR e mais: <span class="mt">apoio garantido em lei</span> durante o tratamento.', "Lei 8.213/1991"),
        "itens": [
            ("Pouco tempo de contribuição<br><em>não</em> impede o auxílio", 'O câncer dispensa a carência do INSS. Você precisa estar segurada e <span class="mt">passar pela perícia</span>.', "Lei 8.213, arts. 26 e 151"),
            ("Aposentadoria<br><em>sem carência</em>", 'Se a incapacidade for definitiva, a aposentadoria por incapacidade permanente <span class="mt">também dispensa a carência</span>.', "Lei 8.213/1991, art. 151"),
            ("Aposentada não paga<br><em>imposto de renda</em>", 'Aposentadoria e pensão de quem tem câncer são isentas de IR. <span class="mt">Vale para o benefício</span>, não para o salário.', "Lei 7.713/1988, art. 6º, XIV"),
            ("O diagnóstico<br>libera o <em>FGTS</em>", 'O saldo pode ser sacado, <span class="mt">inclusive quando o câncer é de um dependente</span>.', "Lei 8.036/1990, art. 20, XI"),
            ("Seu processo tem<br><em>prioridade</em>", "Quem tem doença grave tem tramitação prioritária na Justiça. Separe para pedir:", "CPC, art. 1.048, I"),
        ],
        "checklist": ["Laudo com CID e data do diagnóstico", "Exames e relatório do médico", "Comprovantes de contribuição"],
        "fecho": ("Sua energia é<br>para se <em>cuidar</em>.", "A lei cuida do resto.", "mande para quem está em tratamento."),
        "objetos": ["corte-laco.png", "corte-remedios.png", "corte-ampulheta.png"],
        "foto5": ("cancer-inss", 26), "leticia": ("leticia-ia-26.png", "corte-leticia.png"),
    },
    "violencia-domestica-inss": {
        "tag": "Lei Maria da Penha", "area": "Previdenciário",
        "capa": ("Medida protetiva e trabalho", "5 respostas", "que toda mulher precisa saber",
                 'Você pode se afastar <span class="mt">sem perder o emprego</span>, e o período é pago.', "Lei 11.340/2006"),
        "itens": [
            ("Você pode se afastar<br><em>sem perder</em> o emprego", 'O juiz pode determinar o afastamento do trabalho <span class="mt">por até 6 meses</span>, com o vínculo mantido.', "Lei 11.340/2006, art. 9º, § 2º, II"),
            ("O afastamento<br><em>é pago</em>", 'Empregada: a empresa paga 15 dias e o INSS o restante. <span class="mt">Autônoma: o INSS paga tudo.</span>', "STF, Tema 1.370"),
            ("Peça o afastamento<br>na <em>medida protetiva</em>", 'Ele precisa constar na decisão do juiz. Peça <span class="mt">na delegacia, na Defensoria ou com advogada</span>.', "Lei 11.340/2006"),
            ("Sem perícia:<br>a <em>novidade</em>", 'Parecer da AGU de 01/10/2026 dispensa a perícia quando a decisão comprova o afastamento. <span class="mt">Aguarda o Diário Oficial.</span>', "Parecer AGU, 01/10/2026"),
            ("Você <em>não</em> está<br>sozinha", "Guarde estes contatos:", ""),
        ],
        "checklist": ["Em perigo: ligue 190", "Orientação 24 h e sigilo: Ligue 180", "Cópia da decisão da medida protetiva"],
        "fecho": ("Sua segurança<br>vem <em>primeiro</em>.", "A lei protege também o seu sustento.", "mande para quem pode precisar."),
        "objetos": ["corte-celular.png", "corte-chaves.png", "corte-pasta.png"],
        "foto5": ("violencia-domestica-inss", 18), "leticia": ("leticia-ia-30.png", "leticia-ia-15.png"),
    },
    "mesario-folga": {
        "tag": "Eleições 2026", "area": "Trabalhista",
        "capa": ("Vai ser mesário no 2º turno?", "5 regras", "da sua folga",
                 'Cada dia na seção eleitoral vale <span class="mt">2 dias de folga</span>, sem desconto.', "Lei 9.504/1997, art. 98"),
        "itens": [
            ("Um domingo de eleição<br>vale <em>2 dias</em> de folga", 'Cada dia de trabalho na eleição vale <span class="mt">2 dias de folga</span>.', "Lei 9.504/1997, art. 98"),
            ("O treinamento<br><em>também</em> conta", 'O dia do treinamento é convocação e <span class="mt">também gera folga em dobro</span>.', "Lei 9.504/1997, art. 98"),
            ("Nada sai do<br>seu <em>salário</em>", 'Salário, vale e qualquer outra vantagem <span class="mt">continuam iguais</span> nos dias de folga.', "Lei 9.504/1997, art. 98"),
            ("A empresa não pode<br><em>pagar</em> no lugar", 'Folga não vira dinheiro. <span class="mt">As datas são combinadas</span> entre você e o empregador.', "Lei 9.504/1997"),
            ("Prove com a<br><em>declaração</em>", "Antes de pedir a folga, separe:", ""),
        ],
        "checklist": ["Declaração da Justiça Eleitoral", "Dias de trabalho e de treinamento", "Datas combinadas com o RH"],
        "fecho": ("Domingo de eleição<br>é <em>trabalho</em>.", "E trabalho tem direito.", "mande para quem foi convocado."),
        "objetos": ["corte-carimbo.png", "corte-cafe.png", "corte-reais.png"],
        "foto5": ("mesario-folga", 17), "leticia": ("leticia-ia-34.png", "leticia-real-sorrindo.png"),
    },
    "plano-mamografia": {
        "tag": "Outubro Rosa", "area": "Consumidor",
        "capa": ("Plano de saúde e câncer de mama", "5 coberturas", "que a lei garante",
                 'Desde 01/10, <span class="mt">mamografia em qualquer idade</span> com pedido médico.', "ANS · 01/10/2026"),
        "itens": [
            ("Mamografia em<br><em>qualquer idade</em>", 'Com pedido médico, o plano cobre a mamografia digital <span class="mt">sem limite de idade</span>.', "ANS, desde 01/10/2026"),
            ("Negar por idade<br><em>acabou</em>", 'A cobertura obrigatória era só dos 40 aos 69 anos. <span class="mt">Essa regra caiu.</span>', "ANS, desde 01/10/2026"),
            ("A reconstrução da mama<br>é <em>obrigatória</em>", 'Depois da mastectomia, a cirurgia reconstrutiva <span class="mt">é cobertura obrigatória</span> do plano.', "Lei 9.656/1998, art. 10-A"),
            ("Simetria e aréola<br><em>também</em>", 'Inclui a cirurgia na outra mama para simetria e <span class="mt">a reconstrução da aréola</span>.', "Lei 13.770/2018"),
            ("Negou? Peça<br><em>por escrito</em>", "O plano tem que dar o motivo por escrito. Guarde:", ""),
        ],
        "checklist": ["Pedido médico do exame", "Negativa por escrito, com o motivo", "Protocolo do atendimento"],
        "fecho": ("Seu plano não é<br><em>favor</em>.", "É contrato. E a lei está do seu lado.", "mande para quem tem plano de saúde."),
        "objetos": ["corte-estetoscopio.png", "corte-pasta.png", "corte-laco2.png"],
        "foto5": ("plano-mamografia", 21), "leticia": ("leticia-ia-28.png", "leticia-ia-31.png"),
    },
    "separacao-bens-70": {
        "tag": "Família", "area": "Família",
        "capa": ("Casou depois dos", "70 anos?", "5 respostas sobre bens e herança",
                 'Desde 2024 dá para <span class="mt">escolher o regime de bens</span>. Mas tem regra.', "STF, Tema 1.236"),
        "itens": [
            ("A regra do<br><em>Código Civil</em>", 'Acima de 70 anos, o casamento segue a <span class="mt">separação obrigatória de bens</span>.', "Código Civil, art. 1.641, II"),
            ("Hoje dá para<br><em>escolher</em>", 'Desde fevereiro de 2024, o casal pode afastar a regra <span class="mt">por escritura pública</span>.', "STF, Tema 1.236"),
            ("A mudança<br><em>não</em> volta no tempo", 'Vale para frente. O STJ confirmou que ela <span class="mt">não alcança relações já encerradas</span>.', "STJ, 10/2026"),
            ("Já é casado?<br>Dá para <em>mudar</em>", 'Quem casou antes pode pedir à Justiça a mudança do regime, <span class="mt">com efeitos para o futuro</span>.', "Código Civil, art. 1.639, § 2º"),
            ("Bens comprados<br><em>juntos</em>", "Mesmo na separação obrigatória, o que foi comprado com esforço comum pode ser dividido. Guarde:", "Súmula 377 do STF"),
        ],
        "checklist": ["Certidão de casamento com a data", "Escritura do regime de bens, se houver", "Notas e contratos dos bens comprados"],
        "fecho": ("Amor depois dos 70<br>merece <em>planejamento</em>.", "E evita briga na família depois.", "mande para a família."),
        "objetos": ["corte-chaves.png", "corte-carimbo.png", "corte-pasta.png"],
        "foto5": ("separacao-bens-70", 9), "leticia": ("leticia-ia-19.png", "leticia-real-sentada.png"),
    },
    "licenca-adotante": {
        "tag": "Adoção", "area": "Trabalhista",
        "capa": ("Mãe por adoção:", "5 direitos", "iguais aos da mãe biológica",
                 'O STF fechou em setembro <span class="mt">uma diferença antiga</span> entre as mães.', "STF, ADI 7495"),
        "itens": [
            ("<em>120 dias</em>, qualquer que<br>seja a idade da criança", 'A mãe adotante tem a mesma licença da mãe biológica, <span class="mt">de bebê ou de criança maior</span>.', "CLT, art. 392-A"),
            ("Igual em <em>todos</em><br>os regimes", 'O STF acabou com prazos menores para <span class="mt">servidoras federais e militares</span>.', "STF, ADI 7495 (23/09/2026)"),
            ("A licença começa<br>na <em>guarda</em>", 'Conta da adoção ou da <span class="mt">guarda para fins de adoção</span>.', "CLT, art. 392-A, § 4º"),
            ("Mais <em>60 dias</em><br>em empresas cidadãs", 'Se a empresa aderiu ao Empresa Cidadã, <span class="mt">a prorrogação vale igual</span> para quem adota.', "Lei 11.770/2008"),
            ("Licenças em curso<br><em>já</em> entram", "Quem estava de licença em 23/09/2026 já segue a regra nova. Separe:", "STF, ADI 7495"),
        ],
        "checklist": ["Termo de guarda ou sentença de adoção", "Aviso ao RH com a data de início", "Confirmar se a empresa é Empresa Cidadã"],
        "fecho": ("Família se forma<br>de muitos <em>jeitos</em>.", "O direito é o mesmo.", "mande para quem está adotando."),
        "objetos": ["corte-sapatinho.png", "corte-pasta.png", "corte-ampulheta.png"],
        "foto5": ("licenca-adotante", 10), "leticia": ("leticia-ia-29.png", "corte-leticia.png"),
    },
    "penhora-salario": {
        "tag": "Dívidas", "area": "Consumidor",
        "capa": ("Seu salário pode ser", "penhorado?", "5 respostas depois do STJ",
                 'A regra mudou, mas <span class="mt">tem limites</span>.', "STJ, Tema 1.230"),
        "itens": [
            ("Salário <em>continua</em><br>protegido", 'Em regra, o salário é <span class="mt">impenhorável</span>.', "CPC, art. 833, IV"),
            ("Pensão e salários altos<br><em>sempre</em> puderam", 'Pensão alimentícia e o que passa de <span class="mt">50 salários mínimos</span> já podiam ser penhorados.', "CPC, art. 833, § 2º"),
            ("O que o STJ<br><em>mudou</em>", 'Parte do salário pode ser penhorada para outras dívidas, <span class="mt">em caso excepcional</span>.', "STJ, Tema 1.230"),
            ("O mínimo para viver<br>é <em>intocável</em>", 'Só se outros meios falharem e <span class="mt">sem comprometer a sua subsistência</span>.', "STJ, Tema 1.230"),
            ("Poupança<br><em>protegida</em>", "Até 40 salários mínimos na poupança seguem protegidos. Se receber intimação, guarde:", "CPC, art. 833, X"),
        ],
        "checklist": ["A intimação e o número do processo", "Contas de aluguel, luz, comida, remédio", "Extratos da conta e da poupança"],
        "fecho": ("Dívida se negocia.<br>O mínimo para viver, <em>não</em>.", "Não ignore a intimação.", "mande para quem está endividado."),
        "objetos": ["corte-reais.png", "corte-cofrinho.png", "corte-calculadora.png"],
        "foto5": ("penhora-salario", 27), "leticia": ("leticia-ia-32.png", "leticia-ia-15.png"),
    },
    "bebe-pensao-morte": {
        "tag": "Pensão por morte", "area": "Previdenciário",
        "capa": ("O pai faleceu na gravidez:", "e a pensão?", "5 respostas sobre o direito do bebê",
                 'O bebê pode ter direito <span class="mt">mesmo nascendo depois</span>.', "Lei 8.213/1991"),
        "itens": [
            ("O bebê <em>tem</em> direito,<br>mesmo nascendo depois", 'O filho é dependente do pai no INSS, <span class="mt">mesmo que nasça depois da morte</span>.', "Lei 8.213/1991, art. 16, I"),
            ("O pai precisava<br>ser <em>segurado</em>", 'Na data do óbito, ele precisava estar <span class="mt">contribuindo ou no período de graça</span>.', "Lei 8.213/1991, art. 15"),
            ("Não eram casados?<br>Prove a <em>paternidade</em>", 'Pode ser preciso reconhecer a paternidade, <span class="mt">até por DNA com avós ou irmãos</span>.', ""),
            ("<em>180 dias</em> fazem<br>diferença", 'Pedido em até 180 dias do óbito garante a pensão <span class="mt">desde a data da morte</span>.', "Lei 8.213/1991, art. 74, I"),
            ("Passou do prazo?<br><em>Ainda</em> há caminho", "A Justiça tem garantido atrasados desde o óbito para menores de 16 anos. Separe:", "TRF1, 2026"),
        ],
        "checklist": ["Certidão de óbito do pai", "Certidão de nascimento do bebê", "Prova da contribuição do pai ao INSS"],
        "fecho": ("Nenhuma mãe deveria<br>enfrentar isso <em>sem informação</em>.", "A lei protege o seu filho.", "mande para quem precisa."),
        "objetos": ["corte-ultrassom.png", "corte-sapatinho.png", "corte-ampulheta.png"],
        "foto5": ("bebe-pensao-morte", 21), "leticia": ("leticia-ia-31.png", "leticia-real-sorrindo.png"),
    },
    "banco-encerra-conta": {
        "tag": "Consumidor", "area": "Consumidor",
        "capa": ("O banco pode", "fechar sua conta?", "5 pontos da decisão do STJ",
                 'Pode, mas <span class="mt">não de qualquer jeito</span>.', "STJ, Tema 1.119"),
        "itens": [
            ("O banco <em>pode</em><br>encerrar a conta", 'Até por desinteresse comercial, <span class="mt">não é abusivo por si só</span>.', "STJ, Tema 1.119"),
            ("Mas tem que<br><em>avisar antes</em>", 'A comunicação prévia é obrigatória e <span class="mt">segue as regras do CMN</span>.', "STJ, Tema 1.119"),
            ("O dinheiro<br>é <em>seu</em>", 'O saldo precisa ser devolvido ou transferido. <span class="mt">O banco não pode reter.</span>', "CDC, art. 6º, III"),
            ("Reorganize a vida<br><em>antes</em> do prazo", 'Mude <span class="mt">salário, débitos automáticos e chaves Pix</span> dessa conta.', "STJ, Tema 1.119"),
            ("Sem aviso?<br>Há <em>saída</em>", "Encerramento sem comunicação, que trava o seu dinheiro, pode gerar indenização. Guarde:", "CDC, art. 6º, VI"),
        ],
        "checklist": ["A mensagem ou carta do banco", "Extrato com o saldo na data", "Comprovantes de prejuízo"],
        "fecho": ("O banco pode encerrar.<br>Não pode te deixar <em>sem o seu dinheiro</em>.", "Guarde o aviso e os comprovantes.", "mande para quem recebeu esse aviso."),
        "objetos": ["corte-cartao.png", "corte-celular.png", "corte-cofrinho.png"],
        "foto5": ("banco-encerra-conta", 22), "leticia": ("leticia-ia-27.png", "leticia-ia-30.png"),
    },
}
