"""social_connections e social_metrics

Revision ID: 72f5b73cb465
Revises: 7f5c9d85f0f7
Create Date: 2026-07-20 12:46:40.858592

"""
from alembic import op
import sqlalchemy as sa


revision = '72f5b73cb465'
down_revision = '7f5c9d85f0f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plataforma', sa.String(length=20), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=False),
    sa.Column('ig_user_id', sa.String(length=50), nullable=False),
    sa.Column('nome_conta', sa.String(length=200), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conectado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'plataforma', name='uq_social_connections_tenant_plataforma')
    )
    op.create_table('social_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('referencia_id', sa.Uuid(), nullable=True),
    sa.Column('metricas', sa.JSON(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_metrics')
    op.drop_table('social_connections')
    # ### end Alembic commands ###
