"""scheduled_posts

Revision ID: 7f5c9d85f0f7
Revises: a233bb17f231
Create Date: 2026-07-19 19:00:12.813548

"""
from alembic import op
import sqlalchemy as sa


revision = '7f5c9d85f0f7'
down_revision = 'a233bb17f231'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_piece_id', sa.Uuid(), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('formato', sa.String(length=20), nullable=False),
    sa.Column('data_agendada', sa.Date(), nullable=False),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_piece_id', name='uq_scheduled_posts_content_piece')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_posts')
    # ### end Alembic commands ###
