"""scheduled_posts: platform_post_id e tentativas

Revision ID: c5219c39eacb
Revises: 72f5b73cb465
Create Date: 2026-07-20 13:44:26.025716

"""
from alembic import op
import sqlalchemy as sa


revision = 'c5219c39eacb'
down_revision = '72f5b73cb465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_posts', sa.Column('platform_post_id', sa.String(length=50), nullable=True))
    op.add_column('scheduled_posts', sa.Column('tentativas', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_posts', 'tentativas')
    op.drop_column('scheduled_posts', 'platform_post_id')
    # ### end Alembic commands ###
